# Generated by Django 3.1.7 on 2021-03-07 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='event',
            name='is_liked',
            field=models.ManyToManyField(related_name='events_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
